#!/usr/bin/perl -w

use strict;
use Encode     qw(decode);
use POSIX      qw(floor);
use Gtk3       -init;
use Glib       'TRUE', 'FALSE';
use File::Basename;
use Cwd        qw(abs_path);
use Image::ExifTool;

# Module im gleichen Verzeichnis wie dieses Skript finden
use lib dirname(abs_path($0));
use ExifTagSelector qw(show_tag_selector load_config);
use ExifManual      qw(show_manual);
use ExifAbout       qw(show_about);

#################################################################################
# CSS
#################################################################################
my $css_provider = Gtk3::CssProvider->new;
my $css_styles = <<'END_CSS';
.thumbnail {
    padding: 5px 5px 5px 5px;
}
.thumbnail-focused {
    border: 1px solid lightgreen;
    border-radius: 5px;
    margin:  5px 5px 5px 5px;
}
.exif-separator {
    color: #cccccc;
    background-color: #cccccc;
    min-height: 1px;
}
paned separator {
    color: #cccccc;
    background-color: #cccccc;
    min-width: 1px;
    border: none;
    box-shadow: none;
}
.exif-panel {
    background-color: transparent;
    border-left: 2px solid #cccccc;
}
.exif-title {
    color: transparent;
    font-size: 13px;
    font-weight: bold;
    padding: 6px 8px 4px 8px;
}
treeview {
    background-color: transparent;
    color: #cccccc;
    font-family: "Monospace";
    font-size: 11px;
}
treeview:selected {
    background-color: #e94560;
    color: #ffffff;
}
treeview header button {
    background-color: transparent;
    color: #cccccc;
    border: none;
    font-weight: bold;
    font-size: 11px;
}
END_CSS

my $screen = Gtk3::Gdk::Screen::get_default;
$css_provider->load_from_data($css_styles);
Gtk3::StyleContext::add_provider_for_screen($screen, $css_provider, Gtk3::STYLE_PROVIDER_PRIORITY_USER);

my @imageeventboxes = ();

#################################################################################
# Config laden (Tags + Settings)
#################################################################################
my ($cfg_tags, $cfg_settings) = load_config();

my $cmd_left    = $cfg_settings->{action_left_mousebutton}   || 'chromium --disable-features=GCMRegistration 2>/dev/null';
my $cmd_right   = $cfg_settings->{action_right_mousebutton}  || 'gimp';
my $comment_tag = $cfg_settings->{name_of_exif_edit_comment} || 'Comment';

#################################################################################
# EXIF-Tags Positivliste – aus Config, Fallback auf eingebaute Liste
#################################################################################
my @WANTED_TAGS_DEFAULT = qw(
    FileName Comment FileSize Model LensType FocalLength35efl LensModel
    FocusDistance ImageSize ImageStabilization CreateDate Aperture
    ShutterSpeed DateTimeOriginal ISO RollAngle Rotation Orientation
);
my @WANTED_TAGS = keys %$cfg_tags ? sort keys %$cfg_tags : @WANTED_TAGS_DEFAULT;
my %WANTED      = map { $_ => 1 } @WANTED_TAGS;

#################################################################################
# Global vars
#################################################################################
my $numofcolls        = 6;
my $show_exif_details = 0;

#################################################################################
# Window
#################################################################################
my $window = Gtk3::Window->new('toplevel');
$window->set_default_size(1600, 600);
$window->signal_connect(destroy => sub { Gtk3->main_quit });

my $monitor_width = Gtk3::Gdk::Display::get_default()
                  ->get_primary_monitor()->get_geometry()->{width};
my $thumbsize     = floor(($monitor_width / $numofcolls) - 5 * ($numofcolls + 2) - 55);
my $exifpanelsize = int($monitor_width * 0.125);

print "monitor_width $monitor_width\n";
print "thumbsize $thumbsize\n";
print "exifpanelsize $exifpanelsize\n";

my $vbox_main = Gtk3::Box->new('vertical', 0);
$window->add($vbox_main);
$window->maximize();

#################################################################################
# Menue
#################################################################################
my $accel_group = Gtk3::AccelGroup->new();
$window->add_accel_group($accel_group);
my $menubar = Gtk3::MenuBar->new();

# File
my $menu_datei      = Gtk3::Menu->new();
my $menu_item_datei = Gtk3::MenuItem->new_with_label("File");
$menu_item_datei->set_submenu($menu_datei);

my $menu_item_reload = Gtk3::MenuItem->new_with_label("Reload");
$menu_item_reload->signal_connect(activate => \&load_images);
$menu_item_reload->add_accelerator("activate", $accel_group, Gtk3::Gdk::KEY_r, ['control-mask'], 'visible');
$menu_datei->append($menu_item_reload);

my $menu_item_todel = Gtk3::MenuItem->new_with_label("To Del");
$menu_item_todel->signal_connect(activate => \&todel_images);
$menu_item_todel->add_accelerator("activate", $accel_group, Gtk3::Gdk::KEY_d, ['control-mask'], 'visible');
$menu_datei->append($menu_item_todel);

my $menu_item_quit = Gtk3::MenuItem->new_with_label("End");
$menu_item_quit->signal_connect(activate => sub { Gtk3->main_quit() });
$menu_item_quit->add_accelerator("activate", $accel_group, Gtk3::Gdk::KEY_q, ['control-mask'], 'visible');
$menu_datei->append($menu_item_quit);
$menubar->append($menu_item_datei);

# Settings
my $menu_settings      = Gtk3::Menu->new();
my $menu_item_settings = Gtk3::MenuItem->new_with_label("Settings");
$menu_item_settings->set_submenu($menu_settings);

my $menu_item_tag_selector = Gtk3::MenuItem->new_with_label("Tag Selector");
$menu_item_tag_selector->signal_connect(activate => sub { show_tag_selector($window) });
$menu_item_tag_selector->add_accelerator("activate", $accel_group, Gtk3::Gdk::KEY_t, ['control-mask'], 'visible');
$menu_settings->append($menu_item_tag_selector);
$menubar->append($menu_item_settings);

# ?
my $menu_help      = Gtk3::Menu->new();
my $menu_item_help = Gtk3::MenuItem->new_with_label("?");
$menu_item_help->set_submenu($menu_help);

my $menu_item_manual = Gtk3::MenuItem->new_with_label("Manual");
$menu_item_manual->signal_connect(activate => sub { show_manual($window) });
$menu_item_manual->add_accelerator("activate", $accel_group, Gtk3::Gdk::KEY_h, ['control-mask'], 'visible');
$menu_help->append($menu_item_manual);

my $menu_item_about = Gtk3::MenuItem->new_with_label("About exif_edit");
$menu_item_about->signal_connect(activate => sub { show_about($window) });
$menu_help->append($menu_item_about);
$menubar->append($menu_item_help);

$vbox_main->pack_start($menubar, FALSE, FALSE, 0);

#################################################################################
# Haupt-Bereich: HPaned
#################################################################################
my $hpaned = Gtk3::Paned->new('horizontal');
$vbox_main->pack_start($hpaned, TRUE, TRUE, 0);

my $scroll = Gtk3::ScrolledWindow->new();
$scroll->set_policy('automatic', 'automatic');
$hpaned->pack1($scroll, TRUE, TRUE);

my $vbox_images = Gtk3::Box->new('vertical', 10);
$scroll->add($vbox_images);

my $exif_panel = Gtk3::Box->new('vertical', 0);
$exif_panel->get_style_context->add_class('exif-panel');
$exif_panel->set_size_request($exifpanelsize, -1);
$hpaned->pack2($exif_panel, FALSE, FALSE);

my $exif_title = Gtk3::Label->new('EXIF');
$exif_title->get_style_context->add_class('exif-title');
$exif_title->set_halign('start');
$exif_panel->pack_start($exif_title, FALSE, FALSE, 0);

my $sep = Gtk3::Separator->new('horizontal');
$sep->get_style_context->add_class('exif-separator');
$exif_panel->pack_start($sep, FALSE, FALSE, 0);

my $exif_store = Gtk3::ListStore->new('Glib::String', 'Glib::String');
my $exif_view  = Gtk3::TreeView->new_with_model($exif_store);
$exif_view->set_headers_visible(TRUE);
$exif_view->set_grid_lines('horizontal');

for my $col_def (['Tag', 0, 120], ['Wert', 1, 170]) {
    my ($title, $idx, $width) = @$col_def;
    my $renderer = Gtk3::CellRendererText->new;
    $renderer->set(ellipsize => 'end');
    my $col = Gtk3::TreeViewColumn->new_with_attributes($title, $renderer, text => $idx);
    $col->set_min_width($width);
    $col->set_resizable(TRUE);
    $exif_view->append_column($col);
}

my $exif_scroll = Gtk3::ScrolledWindow->new;
$exif_scroll->set_policy('automatic', 'automatic');
$exif_scroll->add($exif_view);
$exif_panel->pack_start($exif_scroll, TRUE, TRUE, 0);

$window->signal_connect('realize' => sub {
    my $total = $window->get_allocated_width();
    $hpaned->set_position($total - $exifpanelsize - 6);
});

#################################################################################
# EXIF-Panel befuellen
#################################################################################
sub update_exif_panel {
    my ($filepath) = @_;
    $exif_store->clear;

    my $basename = basename($filepath);
    $exif_title->set_markup(
        '<span foreground="#cccccc" font="12" weight="bold">  EXIF: ' . $basename . '</span>'
    );

    my $et = Image::ExifTool->new;
    $et->Options(DateFormat => '%Y-%m-%d %H:%M:%S', Duplicates => 0, RequestAll => 1, Group => 0);
    my $info = $et->ImageInfo($filepath, \@WANTED_TAGS);

    my %seen;
    for my $tag (@WANTED_TAGS) {
        next unless exists $info->{$tag};
        (my $bare = $tag) =~ s/.*://;
        next if $seen{$bare}++;
        my $val = $info->{$tag} // '';
        $val = '(binaer)' if ref $val;
        $val =~ s/[\x00-\x08\x0b\x0c\x0e-\x1f]//g;
        $exif_store->set($exif_store->append, 0, $bare, 1, "$val");
    }

    if (!$exif_store->iter_n_children(undef)) {
        my $info2 = $et->ImageInfo($filepath);
        for my $raw (sort keys %$info2) {
            (my $bare = $raw) =~ s/.*://;
            next unless $WANTED{$bare};
            next if $seen{$bare}++;
            my $val = $info2->{$raw} // '';
            $val = '(binaer)' if ref $val;
            $val =~ s/[\x00-\x08\x0b\x0c\x0e-\x1f]//g;
            $exif_store->set($exif_store->append, 0, $bare, 1, "$val");
        }
    }
}

#################################################################################
# Fokus setzen + EXIF-Panel aktualisieren
#################################################################################
sub set_focus_on {
    my ($focused, $filepath) = @_;
    foreach my $eb (@imageeventboxes) {
        $eb->get_style_context->remove_class('thumbnail-focused');
    }
    $focused->get_style_context->add_class('thumbnail-focused');
    update_exif_panel($filepath) if defined $filepath;
}

#################################################################################
# Todel
#################################################################################
sub todel_images {
    my @images   = glob("*.JPG *.jpg *.png *.PNG *.jpeg *.JPEG");
    my $exifTool = Image::ExifTool->new();
    if (! -d 'todel') { `mkdir todel` }
    foreach my $file (@images) {
        my $comment = $exifTool->ImageInfo($file)->{$comment_tag} // "";
        if ($comment eq 'todel') { `mv $file todel/`; }
    }
    &load_images;
}

#################################################################################
# Widgets entfernen
#################################################################################
sub remove_widget {
    my ($widget) = @_;
    $vbox_images->remove($widget);
}
$vbox_images->foreach(\&remove_widget);

#################################################################################
# Bilder laden
#################################################################################
sub load_images {
    $vbox_images->foreach(\&remove_widget);
    @imageeventboxes = ();
    $exif_store->clear;
    $exif_title->set_markup('<span foreground="#cccccc" font="12" weight="bold">  EXIF</span>');

    my @images    = sort glob("*.JPG *.jpg *.png *.PNG *.jpeg *.JPEG");
    my $actfolder = `pwd`;
    $actfolder =~ s/\n//;
    $window->set_title("exif_edit - $actfolder (" . scalar(@images) . ")");

    my ($row, $i) = (undef, 0);

    foreach my $file (@images) {
        my $pixbuf = Gtk3::Gdk::Pixbuf->new_from_file_at_scale($file, $thumbsize, $thumbsize, TRUE);
        my $image  = Gtk3::Image->new_from_pixbuf($pixbuf);
        $image->get_style_context->add_class('thumbnail');

        my $imageeventbox = Gtk3::EventBox->new();
        $imageeventbox->add($image);
        $imageeventbox->add_events(['button-press-mask']);

        my $captured_file = $file;
        $imageeventbox->signal_connect(button_press_event => sub {
            my ($widget, $event) = @_;
            if    ($event->button == 1) { system("/bin/sh", "-c", "$cmd_left \"$captured_file\" &"); }
            elsif ($event->button == 3) { system("/bin/sh", "-c", "$cmd_right \"$captured_file\" &"); }
            set_focus_on($imageeventbox, $captured_file);
            return TRUE;
        });
        push(@imageeventboxes, $imageeventbox);

        my $exifTool        = Image::ExifTool->new;
        $exifTool->ExtractInfo($file);

        # Rotate/flip thumbnail according to EXIF Orientation
        {
            my $orientation = $exifTool->GetValue('Orientation', 'ValueConv') // 1;
            my $rotated = $pixbuf;
            if    ($orientation == 2) { $rotated = $pixbuf->flip(TRUE);  }                              # Horizontal flip
            elsif ($orientation == 3) { $rotated = $pixbuf->rotate_simple('upsidedown'); }              # 180°
            elsif ($orientation == 4) { $rotated = $pixbuf->flip(FALSE); }                              # Vertical flip
            elsif ($orientation == 5) { $rotated = $pixbuf->rotate_simple('clockwise')->flip(TRUE); }   # 90° CW + H-flip
            elsif ($orientation == 6) { $rotated = $pixbuf->rotate_simple('clockwise'); }               # 90° CW
            elsif ($orientation == 7) { $rotated = $pixbuf->rotate_simple('counterclockwise')->flip(TRUE); } # 90° CCW + H-flip
            elsif ($orientation == 8) { $rotated = $pixbuf->rotate_simple('counterclockwise'); }        # 90° CCW
            $image->set_from_pixbuf($rotated) if $rotated != $pixbuf;
        }

        my $comment         = $exifTool->GetValue($comment_tag, 'PrintConv') // '';
        my $commententry    = Gtk3::Entry->new();
        $commententry->set_text(decode('UTF-8', $comment));
        $commententry->signal_connect(focus_out_event => sub {
            my $tool = Image::ExifTool->new;
            $tool->SetNewValue($comment_tag, $commententry->get_text());
            $tool->WriteInfo($file);
            return FALSE;
        });

        my $label         = Gtk3::Label->new($file);
        my $labeleventbox = Gtk3::EventBox->new();
        $labeleventbox->add($label);
        $labeleventbox->add_events(['button-press-mask']);
        $labeleventbox->signal_connect(button_press_event => sub {
            $commententry->set_text('todel');
            $exifTool->SetNewValue($comment_tag, 'todel');
            $exifTool->WriteInfo($file);
            return TRUE;
        });

        my $vbox = Gtk3::Box->new('vertical', 5);
        $vbox->pack_start($imageeventbox,  FALSE, FALSE, 0);
        $vbox->pack_start($labeleventbox,  FALSE, FALSE, 0);
        $vbox->pack_start($commententry,   FALSE, FALSE, 0);

        if ($i % $numofcolls == 0) {
            $row = Gtk3::Box->new('horizontal', 10);
            $vbox_images->pack_start($row, FALSE, FALSE, 10);
        }
        $i++;
        $row->pack_start($vbox, FALSE, FALSE, 10);
    }

    $vbox_images->show_all();
}

#################################################################################
# Start
#################################################################################
load_images();
$window->show_all();
Gtk3->main();
